version: "3.9"
services:
  expo:
    build: .
    ports:
      - "8081:8081"     # Metro bundler
      - "19000:19000"   # Expo DevTools
      - "19001:19001"   # Tunnel
      - "19002:19002"   # Web UI
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env2
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    stdin_open: true
    tty: true
