version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./cert:/app/cert

    environment:
      - PORT=3001
      - Conn_Strng=mongodb://mongo:27017/hypothyroiddb
      - ADMIN_SECRET=supersecureadminkey123
      - CLIENT_URL=*
      - JWT_SEC=AXZ!@#
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"    
    volumes:
      - mongo-data:/data/db

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command: http --host-header=rewrite app:3001
    environment:
      NGROK_AUTHTOKEN: 2v0o7UvaFhU0VVj5kkAd93jgOfb_57rVityEGqzP8r9sWUvwe
    depends_on:
      - app

volumes:
  mongo-data:
