version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - Conn_Strng=mongodb://mongo:27017/hypothyroiddb
      - ADMIN_SECRET=supersecureadminkey123
      - CLIENT_URL=*
      - JWT_SEC=AXZ!@#
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
